name: Build

on:
  pull_request:
  push:
    branches: [master]

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [ "3.7", "3.8", "3.9"]
        os: [windows-latest, macos-latest]
        platform: [x64, x32]
        exclude:
          - os: macos-latest  
            platform: x32
    steps:
    - uses: actions/checkout@v2

    - name: Setup Conda
      uses: s-weigand/setup-conda@v1
      with:
        activate-conda: false
        conda-channels: conda-forge

    - name: Python ${{ matrix.python-version }}
      shell: bash -l {0}
      run: |
        conda create --name TEST python=${{ matrix.python-version }} numpy cython pip pytest wheel --strict-channel-priority
        source activate TEST
        pip install -e . --no-deps --force-reinstall
        conda info --all
        conda list
    - name: Tests
      shell: bash -l {0}
      run: |
        source activate TEST
        if [ "windows-latest" == "${{ matrix.os }}" ]; then 
           export PKULAST_CFG=$CONDA_PREFIX/Lib/site-packages/pkulast/etc/
        fi
        cd test
        python test.py